[package]
name = "rustvis"
version = "0.1.0"
authors = ["silvi <silviaodwyerdev@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.2"
imageproc = "0.18.0"
time= "^0.1"
rusttype="0.8.3"
palette="*"